### ISSUE TITLE
대기 현황 조회 API

### ISSUE THREAD

**Issue by HJunng** [Team-Blossom-devs/line-up-backend#11]
##  💼 작업 설명

대기 팀 수, 예상 대기 시간을 내려주는 API

##  ✅ To-do

- [x] 예상 대기 시간 알고리즘 짜기
- [x] API 명세서 반영
- [x] 공통 응답 내려주기
