### ISSUE TITLE
QR Code 입장 페이지 구축

### ISSUE THREAD

**Issue by devkeon** [Team-Blossom-devs/line-up-backend#25]
##  💼 작업 설명
QR Code 입장 페이지를 Thymeleaf template 엔진을 사용하여 서버 사이드에서 구현합니다.
QR Code 입장 페이지는 남용의 가능성이 있기 때문에 서버 뒤에 숨겨놔야 한다고 생각하여 서버 사이드에서 구현합니다.

##  ✅ To-do

- [x] natural html 작업
- [x] 퍼블리싱
- [x] js script 작성
- [x] js 파일 분리
