### ISSUE TITLE
배포 후 URL 수정 및 환경변수화

### ISSUE THREAD

**Issue by devkeon** [Team-Blossom-devs/line-up-backend#27]
##  💼 작업 설명
현재 localhost:8080으로 되어있는 url들을 프론트 배포 주소, 서버 주소로 각각 변환 예정

##  ✅ To-do

- [x] QR Code URL 변경 및 환경변수화
- [ ] 서버 요청 URL(axios) 변경 및 환경변수화
- [x] Redriect URL 변경 및 환경변수화
- [ ] RDB URL 변경 및 환경변수화
- [ ] Redis URL 변경 및 환경변수화
