### ISSUE TITLE
S3 버킷 구축 및 사진 업로드 구현

### ISSUE THREAD

**Issue by HJunng** [Team-Blossom-devs/line-up-backend#42]
##  💼 작업 설명

- 연습용 S3 버킷 생성하고 프로젝트에 연결해서 사진을 업로드 할 수 있도록 만듦.
- 주점 이미지 저장하고, 가져오는 부분 수정

##  ✅ To-do

- [ ] S3 버킷 생성 및 연결
- [ ] 사진 업로드 API 구현
- [ ] 주점 정보 가져올 때, 사진 URL 같이 보내도록 수정
- [ ] 사진 가져오는 API 구현
