### ISSUE TITLE
Redis에서 QR코드 가져와, 프론트에 전달

### ISSUE THREAD

**Issue by HJunng** [Team-Blossom-devs/line-up-backend#46]
##  💼 작업 설명

Redis에서 Waiting 정보를 토대로 QR 코드 가져와 프론트에 전달.

##  ✅ To-do

- [ ] Redis에서 key값으로 QR코드 조회
- [ ] 권한 검사 추가
- [ ] PENDING 상태인지 확인 검사
