### ISSUE TITLE
[주점] 운영시간 제외하고 대기 시, 에러 처리

### ISSUE THREAD

**Issue by HJunng** [Team-Blossom-devs/line-up-backend#62]
##  💼 작업 설명

주점의 운영시간 이외의 시간에 대기를 걸게 되면, 에러 처리
Redis의 QR 발급 시간이랑 맞추기

##  ✅ To-do

- [ ] 대기 request를 보낸 시간이 주점 운영시간인지 확인 로직 추가
- [ ] 운영시간이 아니라면 error 처리
- [ ] updatedAt에 맞춰서 seconds로 계산해, 더 정확한 값을 도출하도록 변경
