### ISSUE TITLE
줄서기 현황 리스트 조회

### ISSUE THREAD

**Issue by devkeon** [Team-Blossom-devs/line-up-backend#7]
##  💼 작업 설명
관리자 페이지에서 줄서기 현황 리스트를 내려줍니다.
커서 기반 페이징을 통해 무한 스크롤을 구현하고 현재까지 줄 선 인원을 순서대로 내려줍니다.

##  ✅ To-do
- [x] 커서 기반 페이징 학습
- [x] 카프카 consumer 학습
- [x] 관련 repository 구현 (Waiting)
- [ ] WaitingService 혹은 ManagerService 구현
- [ ] Controller 계층 구현
