### ISSUE TITLE
일반 로그인 기능 구현

### ISSUE THREAD

**Issue by je326** [Team-Blossom-devs/line-up-backend#8]
##  💼  작업 설명

매니저 로그인을 위한 일반 로그인 기능 구현

##  ✅  To-do

- [x] JWT 관련 구현
- [x] Spring Security 설정
- [x] 일반 로그인 API 구현
